name: build

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '15 1 * * *'

jobs:
  build:
    uses: datavisyn/github-workflows/.github/workflows/build-node.yml@main
    secrets: inherit
    with:
      node_version: '24' # TODO: Remove as soon as it's the default

