name: build

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "15 1 * * 1-5" # "At 01:15 on every day-of-week from Monday through Friday.”, see: https://crontab.guru/#15_1_*_*_1-5

jobs:
  build:
    uses: datavisyn/github-workflows/.github/workflows/build-node.yml@main
    secrets: inherit
